[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = false

[[hooks]]
stage = "build"
command = "pnpm"
command_arguments = [
    "tailwindcss",
    "-i",
    "./styles/base.css",
    "-o",
    "./styles/styles.min.css",
    "--minify",
]
